repos:
  - repo: https://github.com/ambv/black
    rev: 23.10.1
    hooks:
      - id: black
        args: ["--line-length=79"]
  - repo: https://github.com/pycqa/isort 
    rev: 5.12.0
    hooks:
      - id: isort
