repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.6

  - repo: https://github.com/pycqa/isort
    rev: 5.6.4
    hooks:
      - id: isort
