[tool.poetry]
name = "ollama-benchmarking"
version = "0.1.0"
description = ""
authors = ["Niklas Alexander Shern <nashern@protonmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
langchain = "0.0.259"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
